### ISSUE TITLE
Can't Build Anything

### ISSUE THREAD

**Issue by duy1998** [aljazsim/validation-framework-for-net#1]
It says about key.pfx, can't find FrameWork.dll. Help me, please! Thank you

**Comment by aljazsim** [comment]
Hi Duy.

Key.pfx is not included in the source control, since it is the private key for signing the assembly before publishing it to NuGet repository. For your development you can simply uncheck the "Sign the assembly" checkbox by right clicking the project in Solution Explorer and selecting Properties in Visual Studio and then clicking on the tab Signing and then you can remove the reference to key.pfx by right clicking it in Solution Explorer and selecting the option "Exclude from project". After that you should be able to build the project without any issues (how assembly signing works: https://docs.microsoft.com/en-us/dotnet/standard/assembly/sign-strong-name).  If you're experiencing any other issues, please let me know.
